version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm i
      - export BUCKET=test-bucket-codepipeline1
      - aws cloudformation package --template-file template.yml --s3-bucket test-bucket-codepipeline1 --output-template-file output_template.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml