AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Output simple sentence.
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Runtime: python3.8
    CodeUri: ./
    Events:
      MyTimeApi:
        Type: Api
        Properties:
          Path: /test-pipeline
          Method: GET